apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-application
spec:
  destination:
    name: 'default'
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/nginx
    repoURL: 'https://gitlab.com/mbaldess/argocd-tests.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
