apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-test-application
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/hello-world
    repoURL: 'https://github.com/mbaldessari/argocd-tests.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
