apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bug-selfheal-application
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/selfheal-bug
    repoURL: 'https://github.com/mbaldessari/argocd-tests.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      selfHeal: true

